name: Backend

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: git submodule update --init --recursive
    - run: npm run build
      env:
        ETHEREUM_RPC: ${{ secrets.ETHEREUM_RPC }}
        POLYGON_RPC: ${{ secrets.POLYGON_RPC }}
        BSC_RPC: ${{ secrets.BSC_RPC }}
  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: git submodule update --init --recursive
    - run: cd DefiLlama-Adapters && git checkout main && git pull
    - name: Deploy infrastructure stack
      run: npm run deploy:prod
      env:
        ETHEREUM_RPC: ${{ secrets.ETHEREUM_RPC }}
        POLYGON_RPC: ${{ secrets.POLYGON_RPC }}
        BSC_RPC: ${{ secrets.BSC_RPC }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
