name: Data

on:
  push:
    branches: [ master ]

defaults:
  run:
    working-directory: data

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      data: ${{ steps.filter.outputs.data }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          data:
            - 'data/**'
  deploy:
    needs: changes
    if: ${{ needs.changes.outputs.data == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm ci
    - name: Deploy infrastructure stack
      run: npm run deploy:prod
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
